const projectCases={
reclutamiento:['Power BI · Excel','Dashboard Ejecutivo de Reclutamiento','Caso de análisis para visualizar el flujo completo de selección, desde la apertura de la vacante hasta la contratación.','Centralizar candidatos, vacantes, etapas y tiempos de cobertura en una sola vista ejecutiva.','Limpieza de datos, modelado de relaciones, definición de indicadores y diseño del dashboard.','Power BI, Excel y modelado de datos'],
'apps-script':['Apps Script','Automatización con Google Apps Script','Flujo diseñado para procesar registros de una hoja, comprobar campos obligatorios y preparar notificaciones sin intervención manual.','Reducir tareas repetitivas, errores de registro y tiempos de respuesta.','Validación de entradas, aplicación de reglas automáticas, actualización de estados y notificaciones programadas.','Google Sheets, Apps Script y JavaScript'],
qa:['Data Quality','QA de datos','Proceso de revisión para identificar registros incompletos, duplicados, formatos inconsistentes y valores fuera de las reglas establecidas.','Aumentar la confianza en la información antes de utilizarla en reportes.','Creación de controles de nulos, duplicados, formatos, rangos y reglas de negocio.','Excel, SQL y criterios de calidad de datos'],
excel:['Excel','Tracker Excel','Herramienta de seguimiento operativo con estados, responsables, fechas y alertas visuales para organizar el trabajo diario.','Dar visibilidad al avance, los pendientes y las prioridades del equipo.','Diseño de tabla estructurada, validaciones, fórmulas, estados e indicadores visuales.','Excel, fórmulas y tablas dinámicas'],
sql:['T-SQL','SQL Server','Colección de consultas para integrar tablas, resumir información y preparar datos que puedan consumirse en reportes.','Convertir registros operativos en información lista para analizar.','Construcción de joins, agregaciones, filtros, vistas y procedimientos almacenados.','SQL Server, T-SQL y modelado relacional'],
java:['Java','Aplicación Java Swing','Aplicación de escritorio orientada al registro y consulta de información mediante formularios y controles de validación.','Gestionar información desde una interfaz clara y mantener organizada la lógica del sistema.','Construcción de formularios, validaciones, eventos y separación de la lógica de negocio.','Java, Swing y programación orientada a objetos']};
const projectDialog=document.querySelector('#project-dialog');
document.querySelectorAll('.view-project').forEach(btn=>btn.addEventListener('click',()=>{const p=projectCases[btn.closest('.project').dataset.project];['modal-tag','modal-title','modal-description','modal-objective','modal-process','modal-tools'].forEach((id,i)=>document.querySelector('#'+id).textContent=p[i]);projectDialog.showModal()}));
projectDialog.querySelector('.close').addEventListener('click',()=>projectDialog.close());projectDialog.addEventListener('click',e=>{if(e.target===projectDialog)projectDialog.close()});
